dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="fourcolor"
  - OPAM_SWITCH="4.07.0+flambda"
  matrix:
  # - COQ_VERSION="8.6"
  - COQ_VERSION="8.7"
  - COQ_VERSION="8.8"
  # - COQ_VERSION="8.9"
  - COQ_VERSION="dev"

install: |
  # Prepare the COQ container
  docker pull "coqorg/coq:${COQ_VERSION}"
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} "coqorg/coq:${COQ_VERSION}"
  docker exec COQ /bin/bash --login -c "
    # This bash script is double-quoted to interpolate Travis CI env vars:
    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex  # -e = exit on failure; -x = trace for debug
    # Using flambda makes sense here as we usually get ~10% faster
    # builds in math-comp.
    opam switch set "$OPAM_SWITCH"
    eval $(opam env)
    opam update -y
    opam install -y -j ${NJOBS} coq-mathcomp-ssreflect coq-mathcomp-algebra
    opam config list
    opam repo list
    opam list
    "
script:
- echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
    eval $(opam env)
    make -j "$NJOBS"
    make install
    "
- docker stop COQ  # optional
- echo -en 'travis_fold:end:script\\r'
