fullname: The Four Color Theorem
shortname: fourcolor
organization: coq-community
community: true
action: true

synopsis: >-
  Mechanization of the Four Color Theorem in Coq

description: |-
  This library contains a formal proof of the Four Color Theorem in Coq,
  along with the theories needed to support stating and then proving the Theorem.
  This includes an axiomatization of the setoid of classical real numbers,
  basic plane topology definitions, and a theory of combinatorial hypermaps.

publications:
- pub_url: https://www.ams.org/notices/200811/tx081101382p.pdf
  pub_title: Formal Proof—The Four-Color Theorem
- pub_url: https://inria.hal.science/hal-04034866/document
  pub_title: A computer-checked proof of the Four Color Theorem

authors:
- name: Georges Gonthier
  initial: true

maintainers:
- name: Yves Bertot
  nickname: ybertot

opam-file-maintainer: palmskog@gmail.com

opam-file-version: dev

license:
  fullname: CeCILL-B
  identifier: CECILL-B

supported_coq_versions:
  text: 8.16 or later
  opam: '{>= "8.16"}'

tested_coq_opam_versions:
- version: '2.1.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '2.1.0-coq-8.18'
  repo: 'mathcomp/mathcomp'
- version: '2.2.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '2.2.0-coq-8.19'
  repo: 'mathcomp/mathcomp'
- version: '2.2.0-coq-dev'
  repo: 'mathcomp/mathcomp'
- version: 'coq-8.19'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'

# test master every Sunday at 05:00 UTC
# (mathcomp/mathcomp-dev is rebuilt every day at 04:00 Paris time)
ci_cron_schedule: '0 5 * * 0'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{>= "2.1.0"}'
  description: |-
    [MathComp ssreflect 2.1.0 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-algebra
  description: |-
    [MathComp algebra](https://math-comp.github.io)
- opam:
    name: coq-hierarchy-builder
    version: '{>= "1.5.0"}'
  description: |-
    [Hierarchy Builder](https://github.com/math-comp/hierarchy-builder) 1.5.0 or later

namespace: fourcolor

keywords:
- name: Four color theorem
- name: small scale reflection
- name: Mathematical Components

categories:
- name: Mathematics/Combinatorics and Graph Theory

build: |-
  ## Building and installation instructions
  
  The easiest way to install the latest released version of The Four Color Theorem
  is via [opam](https://opam.ocaml.org/doc/Install.html):
  
  ```shell
  opam repo add coq-released https://coq.inria.fr/opam/released
  opam install coq-fourcolor
  ```

  If you are only interested in the formalization of real numbers, you can install
  it separately:

  ```shell
  opam repo add coq-released https://coq.inria.fr/opam/released
  opam install coq-fourcolor-reals
  ```
  
  To instead build and install the whole project manually from the repository, do:
  
  ``` shell
  git clone https://github.com/coq-community/fourcolor.git
  cd fourcolor
  make   # or make -j <number-of-cores-on-your-machine> 
  make install
  ```

documentation: |-
  ## Documentation

  The [Four Color Theorem](https://en.wikipedia.org/wiki/Four_color_theorem) (Appel & Haken, 1976) is a landmark result of graph theory.

  The formal proof is based on the [Mathematical Components](https://github.com/math-comp/math-comp) library.
