jobs:
  coq:
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cachix install
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - name: Cachix setup coq
      uses: cachix/cachix-action@v8
      with:
        name: coq
    - name: Cachix setup coq-community
      uses: cachix/cachix-action@v8
      with:
        name: coq-community
    - name: Cachix setup math-comp
      uses: cachix/cachix-action@v8
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: math-comp
    - id: stepCheck
      name: Checking presence of CI target coq
      run: "nb_dry_run=$(NIXPKGS_ALLOW_UNFREE=1 nix-build --no-out-link \\\n --argstr\
        \ bundle \"8.12\" --argstr job \"coq\" \\\n --dry-run 2>&1 > /dev/null)\n\
        echo ::set-output name=status::$(echo $nb_dry_run | grep \"built:\" | sed\
        \ \"s/.*/built/\")\n"
    - if: steps.stepCheck.outputs.status == 'built'
      name: Building/fetching current CI target
      run: NIXPKGS_ALLOW_UNFREE=1 nix-build --no-out-link --argstr bundle "8.12" --argstr
        job "coq"
  fourcolor:
    needs:
    - coq
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cachix install
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - name: Cachix setup coq
      uses: cachix/cachix-action@v8
      with:
        name: coq
    - name: Cachix setup coq-community
      uses: cachix/cachix-action@v8
      with:
        name: coq-community
    - name: Cachix setup math-comp
      uses: cachix/cachix-action@v8
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: math-comp
    - id: stepCheck
      name: Checking presence of CI target fourcolor
      run: "nb_dry_run=$(NIXPKGS_ALLOW_UNFREE=1 nix-build --no-out-link \\\n --argstr\
        \ bundle \"8.12\" --argstr job \"fourcolor\" \\\n --dry-run 2>&1 > /dev/null)\n\
        echo ::set-output name=status::$(echo $nb_dry_run | grep \"built:\" | sed\
        \ \"s/.*/built/\")\n"
    - if: steps.stepCheck.outputs.status == 'built'
      name: 'Building/fetching previous CI target: coq'
      run: NIXPKGS_ALLOW_UNFREE=1 nix-build --no-out-link --argstr bundle "8.12" --argstr
        job "coq"
    - if: steps.stepCheck.outputs.status == 'built'
      name: 'Building/fetching previous CI target: mathcomp-algebra'
      run: NIXPKGS_ALLOW_UNFREE=1 nix-build --no-out-link --argstr bundle "8.12" --argstr
        job "mathcomp-algebra"
    - if: steps.stepCheck.outputs.status == 'built'
      name: Building/fetching current CI target
      run: NIXPKGS_ALLOW_UNFREE=1 nix-build --no-out-link --argstr bundle "8.12" --argstr
        job "fourcolor"
name: Nix CI for bundle 8.12
'on':
  pull_request:
    branches:
    - '**'
  push:
    branches:
    - master
